CREATE TABLE IF NOT EXISTS statistics (
    id BIGINT(15) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    app VARCHAR,
    uri VARCHAR,
    ip VARCHAR,
    moment TIMESTAMP WITHOUT TIME ZONE NOT NULL
);